### ISSUE TITLE
Config not working

### ISSUE THREAD

**Issue by Stoabrogga** [azerothcore/mod-npcbeastmaster#4]
commit Beastmaster: https://github.com/azerothcore/mod-npcbeastmaster/commit/e78d924e18973485f178178eee9c4b120046da23
commit Azerothcore: https://github.com/azerothcore/azerothcore-wotlk/commit/842ac4c14c0f0b650f2efa863ca81ff59866128c
OS: Ubuntu 16.04

The configuration file cannot be read because the path is missing. I fixed this on my fork (amongst other things):
https://github.com/Stoabrogga/mod-npcbeastmaster

**Comment by BarbzYHOOL** [comment]
Can you open a PR for this? It's the same issue on all modules but it would be nice if you made the PR yourself instead of someone else (so you get all credits and know how to do it)

**Comment by Stoabrogga** [comment]
Fixed with the newest commit

**Comment by BarbzYHOOL** [comment]
ty

you can join the discord if you want, we are friendly!
